# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50037f01897fe0f73a90781d4b1028f8260da35a0031c9ca3ab50c74afc9f84c9fd5283d28895ce3431c8bb7f7df2016e81bdc6d01214b753e37bec9ead26448

test:
  secret_key_base: cb943c7f5205c1dfe5d9042485e435d80d2217eec6bd86fb5b46360a5c94fc347e14d966c0210fe30b43c693abb55766a45ce0128447edb28d1be68c89a49dad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
